[versions]
jna = "5.12.1"
jcodec = "0.2.5"
proguard-gradle = "7.2.2"
kotlin = "1.7.20"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.4.0"
kotlinx-atomicfu = "0.18.3"
node = "16.9.1"
android-build-gradle = "7.0.4"
gson = "2.8.6"
#gradle-publish-plugin = "1.0.0"
gradle-publish-plugin = "0.14.0"
closure-compiler = "v20210808"
jackson-version = "2.13.4"

[libraries]
jna-core = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jcodec-core = { module = "org.jcodec:jcodec", version.ref = "jcodec" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard-gradle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gradle-publish-plugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradle-publish-plugin" }
closure-compiler = { module = "com.google.javascript:closure-compiler", version.ref = "closure-compiler" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }

[bundles]
jna = ["jna-core", "jna-platform"]

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#jmh = { id = "me.champeau.jmh", version = "0.6.5" }
